services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "8080:80"
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=botaqualquercoisa
      - IPAM_DATABASE_NAME=phpipam
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    networks:
      phpipam-network:
        ipv4_address: 172.21.100.10

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=botaqualquercoisa
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    networks:
      phpipam-network:
        ipv4_address: 172.21.100.11

  phpipam-mariadb:
    build: .
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=botaqualquercoisa
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mariadb
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      phpipam-network:
        ipv4_address: 172.21.100.12

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:

networks:
  phpipam-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${CUSTOM_NETWORK_SUBNET}
          gateway: ${CUSTOM_NETWORK_GATEWAY}
